# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagories',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='catagories',
            new_name='categories',
        ),
    ]
