# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 10:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Draft',
            new_name='draft',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
