# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0002_forgotpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('catagorystate', models.BooleanField(default=True)),
            ],
        ),
    ]
