# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0002_blog_draft'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='attachments',
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
