# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0003_auto_20170417_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.FileField(upload_to='blogimages/')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='attachments',
        ),
        migrations.AddField(
            model_name='blogfile',
            name='blog',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ebs.Blog'),
        ),
    ]
