# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0003_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='blogimages/')),
                ('tags', models.CharField(max_length=125)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('published', models.DateTimeField()),
                ('publishedstate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.AddField(
            model_name='blog',
            name='catagories',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ebs.Catagories'),
        ),
        migrations.AddField(
            model_name='blog',
            name='organisation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ebs.Organisation'),
        ),
    ]
