# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0004_forgotpassword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='publishedstate',
            new_name='published_state',
        ),
    ]
