# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0005_auto_20170418_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='username',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='forgotpassword',
        ),
    ]
