# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0005_auto_20170420_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='commentstate',
            new_name='comment_state',
        ),
    ]
