# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0006_auto_20170420_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpassword',
            name='username',
        ),
        migrations.DeleteModel(
            name='ForgotPassword',
        ),
    ]
