# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0008_auto_20170420_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_state',
        ),
    ]
