# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0009_remove_blog_comment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_state',
            field=models.BooleanField(default=True),
        ),
    ]
