# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0010_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_count',
            field=models.BooleanField(default=False),
        ),
    ]
