# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-20 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0010_blog_comment_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='comment_state',
            new_name='commentstate',
        ),
    ]
