# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 10:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0011_blog_published_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_count',
            new_name='is_enable',
        ),
    ]
