# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-23 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebs', '0012_auto_20170504_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
