# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 17:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=225)),
                ('blogdescription', models.CharField(max_length=225)),
                ('blogimage', models.ImageField(upload_to='Companyblog')),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('orglogo', models.ImageField(upload_to='Companylogo')),
                ('orguser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('contactno', models.CharField(blank=True, max_length=16)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateform.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation_socialaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faceaccount', models.CharField(max_length=125)),
                ('twitaccount', models.CharField(max_length=125)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plateform.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_role', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='registereduser',
            name='role',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='plateform.Role'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='status',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='plateform.Status'),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisation',
            name='role',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='plateform.Role'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='status',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='plateform.Status'),
        ),
    ]
